# 에이전트별 지식 관리 태스크 설정

# 각 에이전트가 작업 후 정리할 지식 관리 태스크 설정
task_config:
  title: "{agent_name} 작업 지식 정리"
  description: >
    {agent_name}로서 이번 작업에서 얻은 핵심 노하우와 발견 사항을 정리하고 
    지식 관리 도구를 통해 저장하세요. 정리해야 할 내용:
    
    1. 작업 과정에서 발견한 중요한 패턴이나 원칙
    2. 향후 비슷한 작업에 적용할 수 있는 효과적인 접근법
    3. 작업 중 마주친 문제와 해결 방법
    4. 다른 팀원과 공유하면 도움이 될 만한 인사이트

  expected_output: >
    지식 관리 시스템에 정리된 노하우와 발견 사항들. 지식은 md 파일 형태로 
    knowledge/{agent_name}/ 디렉토리에 저장되며, ChromaDB를 통해 검색 가능합니다. 